### ISSUE TITLE
Elfatherm E8.0321

### ISSUE THREAD

**Issue by comtechnik** [fknipp/python-can-loxone-heating-integration#1]
habe deinen Eintrag gefunden.
Ich habe eine Elfatherm E8.0321 einen Raspberry Pi400 und einen Innomaker USB2CAN Adapter.
Ich würde die Elfatherm E8.0321 gerne auslesen. Da ich aber keine Loxon zur Verfügung habe sondern nur einen IOBroker oder Home Assistent habe ich nun eine Frage.
Kann man die E8 und den USB2CAN Adapter auch auslesen und per Mqtt die Daten an den IOBroker senden, oder die Daten mit dem CAN_BUS Adapter vom IOBroker einlesen. Hast du damit Erfahrung. Wäre sehr dankbar für deine Hilfe.

Danke
SG Robert

**Comment by fknipp** [comment]
Hallo Robert!

Ja, das sollte möglich sein. Das Programm unter https://github.com/fknipp/canpicker lässt sich durch einen MQTT-Client erweitern. Orientier Dich einfach am HTTP-Client.

Gutes Gelingen!

**Comment by comtechnik** [comment]
Danke für deine schnelle Antwort,
versteh noch nicht ganz wie ich es mit einen MQTT-Client erweitern kann und wie du das meinst mit "Orientier Dich einfach am HTTP-Client."

**Comment by fknipp** [comment]
Sorry für die späte Antwort, ich bin beim Aufräumen des Mailpostfachs über die Frage gestoßen.

Die *Datensenke* über HTTP ist in https://github.com/fknipp/canpicker/blob/main/canpicker/datasinks/http.py implementiert. Für MQTT muss nur im **\_\_init\_\_** die Verbindung zum MQTT-Broker geöffnet werden (mit `mqttc = mqtt.Client(); mqttc.connect(*server*)`), in **send**  die Nachricht geschickt werden (`mqtt.publish(*topic*, *message*)`).

Alles Gute bei der Umsetzung!
